name: Android Build

on:
  push:
    branches:
      - main  # Change this to your main branch name (e.g., master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.2.0
        with:
          ndk-version: r25c

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Dump versions
        run: ./gradlew --version; cmake --version; ls -l liblsl/lslboost/boost/tti/gen/namespace_gen.hpp

      - name: Build APK
        run: ./gradlew assembleDebug  # Change 'assembleDebug' to 'assembleRelease' if you want a release build

      #- name: Sign app APK
      #  uses: r0adkll/sign-android-release@v1
      #  # ID used to access action output
      #  id: sign_app
      #  with:
      #    releaseDirectory: app/build/outputs/apk/release
      #    signingKeyBase64: ${{ secrets.SIGNING_KEY }}
      #    alias: ${{ secrets.SIGNING_KEY_ALIAS }}
      #    keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
      #    keyPassword: ${{ secrets.KEY_PASSWORD }}

      #- name: Upload APK artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: HelloResolver  # Change this to your desired artifact name
      #    path: ${{steps.sign_app.outputs.signedReleaseFile}}  # Change the path to the location of your APK file







